version: '3.9'

services:
  python:
    container_name: transcript-whisper
    build: 
     dockerfile: docker/Dockerfile
     context: .
    env_file: 
      - .env 
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
    volumes:
      - ./docker_share:/usr/src/docker_share
      - ./key.json:/key.json
    tty: true

